version: '3.1'

services:
    zookeeper:
        image: zookeeper
        deploy:
            restart_policy:
                condition: on-failure 
        #ports:
            #- 2181:2181               
                
    rabbit:
        image: rabbitmq:3-management
        deploy:
            restart_policy:
                condition: on-failure      
        ports:
            - 15672:15672         
            #- 5672:5672
                                
    rest-cat:
        image: rest-cat
        deploy:
            restart_policy:
                condition: on-failure
            placement:
                constraints:
                - node.role == manager                
        environment:
            RABBIT_HOST: rabbit
            RABBIT_PORT: 5672
            RABBIT_USERNAME: guest
            RABBIT_PASSWORD: guest
            INFLUX_URI: http://influx:8086
            ZOOKEEPER_CONNECT_STRING: zookeeper:2181
        ports:
            - 8083:8080      
        depends_on:
            - zookeeper
            - rabbit          
            - influx          
            
    cat-worker:
        image: cat-worker
        deploy:
            restart_policy:
                condition: on-failure                
        environment:
            RABBIT_HOST: rabbit
            RABBIT_PORT: 5672
            RABBIT_USERNAME: guest
            RABBIT_PASSWORD: guest
            ZOOKEEPER_HOST: zookeeper
            INFLUX_URI: http://influx:8086
        depends_on:
            - zookeeper
            - rabbit   
            
    influx:
        image: influxdb
        environment:
            INFLUXDB_DB: mydb
        volumes:
            - influx:/var/lib/influxdb
                    
    rabbit-reporter :
        image: rabbit-reporter
        environment:
            RABBIT_HOST: rabbit
            RABBIT_PORT: 15672
            RABBIT_USERNAME: guest
            RABBIT_PASSWORD: guest
            INFLUX_HOST: influx
            INFLUX_PORT: 8086
            INFLUX_DB: mydb
        depends_on:
            - rabbit
            - influx    
            
    chronograf :
        image: chronograf
        command: chronograf --influxdb-url=http://influx:8086
        environment:
            INFLUX_HOST: influx
            INFLUX_PORT: 8086
            INFLUX_DB: mydb
        depends_on:
            - influx                
        ports:
            - 8888:8888      
        deploy:
            resources:
                limits:
                    cpus: '0.10'
                    memory: 100M
                reservations:
                    cpus: '0.05'
                    memory: 50M         
                    
    cadvisor:
        image: google/cadvisor
        ports:
            - 0.0.0.0:8080:8080
        hostname: '{{.Node.ID}}'
        command: -logtostderr -docker_only -storage_driver=influxdb -storage_driver_db=mydb -storage_driver_host=influx:8086
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:rw
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
        depends_on:
            - influx
        deploy:
            mode: global
            resources:
                limits:
                    cpus: '0.10'
                    memory: 50M
                reservations:
                    cpus: '0.05'
                    memory: 25M
                    
    kapacitor:
        image: kapacitor
        ports:
            - 9092:9092
        depends_on:
            - influx
        environment:      
            KAPACITOR_INFLUXDB_0_URLS_0: http://influx:8086            
        deploy:
            resources:
                limits:
                    cpus: '0.10'
                    memory: 100M
                reservations:
                    cpus: '0.05'
                    memory: 50M                    
            
                                
volumes:
  influx:
    driver: local
    