version: '3.1'

services:     
    
    rabbit:
        image: rabbitmq:3-management
        deploy:
            restart_policy:
                condition: on-failure      

    influx:
        image: influxdb
        environment:
            INFLUXDB_DB: mydb
        volumes:
            - influx:/var/lib/influxdb            
            
    prise:
        image: prise
        environment:
            RABBIT_HOST: "rabbit"
            RABBIT_PORT: "5672"
            RABBIT_USERNAME: "guest"
            RABBIT_PASSWORD: "guest"
            INFLUX_URI: "http://influx:8086"
        ports:
            - "8080:8080"
            
            
    pylog2prov:
        image: pylog2prov
        environment:
            RABBIT_HOST: "rabbit"
            RABBIT_PORT: "5672"
            RABBIT_USERNAME: "guest"
            RABBIT_PASSWORD: "guest"
            
    


volumes:
  influx:
