version: '3.1'

services:
    prometheus:
        image: prom/prometheus:latest
        volumes:
        - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
        command:
        - '-config.file=/etc/prometheus/prometheus.yml'
        ports:
        - '9090:9090'
            
    cadvisor:
        image: google/cadvisor:latest
        ports:
            - "8081:8080"
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:rw
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
            
    grafana:
        image: grafana/grafana
        environment:
            DS_NAME: "Prometheus"
            DS_TYPE: "Prometheus"
            DS_ACCESS: "proxy"
            DS_URL: "http://prometheus:9090"
            DS_DB: "mydb"
        ports:
            - "3000:3000"
        volumes:
            - grafana:/var/lib/grafana
        depends_on:
            - service
        deploy:
            replicas: 1           
         
    service:
        image: eliaskhaldi/my_image
        ports:
            - "8080:8080"
        deploy:
            replicas: 1             
    


volumes:
  grafana:
