version: '3.1'

services:
    prometheus:
        image: prom/prometheus:latest
        volumes:
        - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
        command:
        - "--config.file=/etc/prometheus/prometheus.yml"
        ports:
        - '9090:9090'
            
    cadvisor:
        image: google/cadvisor:latest
        ports:
            - "8081:8080"
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:rw
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
         
    service:
        image: eliaskhaldi/my_image
        ports:
            - "8080:8080"
        deploy:
            replicas: 1             
    


volumes:
  grafana:
