version: '3.1'

services:     
	prometheus:
		image: prom/prometheus:latest
		container_name: prometheus
		ports:
		- 9090:9090
		command:
		- --config.file=/etc/prometheus/prometheus.yml
		volumes:
		- ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
		
    cadvisor:
        image: google/cadvisor
        ports:
            - "8081:8080"
        hostname: '{{.Node.ID}}'
        command: -logtostderr -docker_only -storage_driver=influxdb -storage_driver_db=mydb -storage_driver_host=prometheus:9090
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:rw
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
        depends_on:
            - prometheus
        deploy:
            mode: global                
            
    grafana:
        image: grafana/grafana
        environment:
            DS_NAME: "Prometheus"
            DS_TYPE: "Prometheus"
            DS_ACCESS: "proxy"
            DS_URL: "http://prometheus:9090"
            DS_DB: "mydb"
        ports:
            - "3000:3000"
        volumes:
            - grafana:/var/lib/grafana
        depends_on:
            - prometheus
        deploy:
            replicas: 1           
         
    service:
        image: eliaskhaldi/my_image
        ports:
            - "8080:8080"
        deploy:
            replicas: 1             
    


volumes:
  prometheus:
  grafana:
