scrape_configs:
    - job_name: 'prometheus'
      target_groups:
          - targets: ['localhost:9090']
    - job_name: 'cadvisor'
      scrape_interval: 1s
      target_groups:
          - targets: ['cadvisor:8081']