global:
    scrape_interval: 1m
scrape_configs:
    - job_name: 'prometheus'
        static_configs:
            - targets: ['localhost:9090']
    - job_name: 'cadvisor'
        scrape_interval: 1s
        static_configs:
            - targets:
                - cadvisor:8081