apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: rabbit
  name: rabbit
spec:
  ports:
  - name: "15672"
    port: 15672
    nodePort: 15672
  - name: "5672"
    port: 5672
    nodePort: 5672
  selector:
    io.kompose.service: rabbit
status:
  loadBalancer: {}
