apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: rest-cat
  name: rest-cat
spec:
  ports:
  - name: "8083"
    port: 8083
    targetPort: 8080
  selector:
    io.kompose.service: rest-cat
status:
  loadBalancer: {}
